services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: checksy
      POSTGRES_PASSWORD: checksy_dev
      POSTGRES_DB: checksy_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
